[package]
name = "optimizely"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
thiserror = "1.0"
anyhow = "1.0"
ureq = "2.5.0"
