max_width = 120
fn_call_width = 100
attr_fn_like_width = 100
struct_lit_width = 20
struct_variant_width = 40
array_width = 60
chain_width = 60
single_line_if_else_max_width = 60
fn_params_layout = "Compressed"
# wrap_comments = true
# comment_width = 120
# format_code_in_doc_comments = true
